branches:
  only:
  - master
language: ruby
sudo: required
rvm:
- 2.2.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- sudo apt-get install expect
- chmod +u heroku.exp
- ./heroku.exp
- heroku pg:pull DATABASE_URL travis_ci_test --app hackduke-api
script: bundle exec rspec spec
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: OGRfRoGnJB5xpW3jM3gxqS0uO3XAg0ICcKChLdaWIkF07+xtgopFz8plkNQGL+g5wuohQh2xdB7zvUshTVnrMBZMN7XmlMuIr5aEBbh7XRb0PaR2kX4akblpAnFW/edn1fvwjR6O/ShxVU4FYlLVD3bSEzkAyppETGNx/fZWto8K/gNv02Jwok5zCd9iO6cehg59/3M9Y+57CL7gGfvXGpub6IDF8ug7NV6XtRXCmOvNP9cCZbTEPqOTQvEZiisbQ0HclyL5SyClbwg6yvYUoGfIvWiFgwhqGQSBAlPqC0w6wtqRCAWiFmGip9sUyspFZ3WdOgzPsMNOVu8hpxsnLPTItH8TEugdOeKUMDcvOrjTmVrj+5OMlaSw/7+fS/UqH/Yj6QViOpW3mc3sBRsFkMA87s68WuKB3AS3izc8On2SIyjsAIgHb9I+L2O+MfFUtF/3sygCI+KXySVnXveOtJeDm1DVbE5IHQN1KsSPomLyAy+sfGPECxq6JJxXpLg2OFK/ebW2Hi+YlqjgvLy61F0Pt4vZJrOjxvOery4Xt1hJ3stT5gU0lm1T+TbQ+Rwn3Nf2NSj7IugmBczCcn6+48P4fdMWPQLiRGjKTglJ8DLt4vmCb2MdDfiNj3T1wrRFE110RX1v1n7fdT4wxU7YZAvCRGvdzDToe6RxoJ2O6o4=
  app: hackduke-api
  on:
    repo: hack-duke/hackduke-api
