branches:
  only:
  - master
language: ruby
rvm:
- 2.2.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rspec spec
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: RtvDbKxigWx8bhuFb8YRpTHLUzhf82CSHAM1rNv7lnNgUIz3oDcaGbZ0Bgu1tXgLBIgSwvtjQb6uw7/f76enVIUOHBoxWJtNcjdrCjmi0HdkvKcU0RZIflou4PXKWQ1KAqg0pXZ1Xlnq6noXbokLAmk4m5frMK8riOAS1XQa0sAjOVEk3Hn3lBBQQ66aStbQpuz6lNnZq/qrZ7j6DHv8oUSf31bNSvtubQ7f6qR3GqA9uvLOezJW0MU7yQLEiqL+rPJgWCc769kWyxZF8jW6OUd6wmsXxYY8Ozqgfbp4BjdPyLA4OeS7cnsu2/h0tHVFx0y7tbfurps2sQVF0xwhreYYgCos/mUTsZ+gw6zRB3C5iiwtAAR8HjEPNxrswIBgibLMqGmzrQC+YaJMzxWr98yKgRoAl/E8HmwtOJWAsolfelIKSsTNbdO6j/qhKi9IWtapSzSYBdjCliHFxg9G/8AEoCocNqixkprtc2Ne8IcLTyQSSTa9mq5S5Z7vgYO2yU+CK0kOyHpP9V2vdadoVjiRjuZVQVrD2XPO3hbmb2tmJJUFhn5tctN3xzowMqDcOsJImeDhcVEwCjSxQVu1CGecCUTgLabS5moxvSbCmOPe4WkBY76fqT/bfeHlR2mH8Yq2Xv84h7UOGPODslpHCuL70+X/MVlylSYPb5NTGHQ=
  app: hackduke-api
  on:
    repo: hack-duke/hackduke-api
