branches:
  only:
  - master
language: ruby
sudo: required
dist: trusty
rvm:
- 2.2.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- dropdb travis_ci_test
- heroku pg:pull DATABASE_URL travis_ci_test --app hackduke-api
- bin/rails db:migrate RAILS_ENV=test
script: bundle exec rspec spec
addons:
  postgresql: '9.5'
deploy:
  provider: heroku
  api_key:
    secure: E5xXP8tRjNtt8sa/mDavhS+pN4VuCCD0kfAWJ4/FK+vWATbl2vEvxA/4uqrsSYtOvbfNDfSBsbAdNaPX01YnVfr0ArKTQcaHAZLDBQ2lwlyWZ20ksttME+UIVOWX5JW/4t3BbcXRpl4hIVCdwfO+FQhWs5lxtUOzLzFGhi/2MoaiJsCkxr5NIF63uJEOh+sPDUDpaGNV/hAh0cY+9DVJSmU8bTfXhxfwqWPPj3THlD/ojRDqI11xpbXpH+7RCEvgkgtW5sRcWW/EZ2gIA1SszgAbgU5zE01mWIZatK34Z3xoCrCYYddQHDajT3xoLvb/3vSHz98fOG9W96JItiiIlVwcRLz2swGa1dg0yaVlT/XFZGlZBgE7LbkYECJLFF4dB9NnuJZT5zvsmVARQWb1bwyEO/3vLLnmKiah2HJA9fP3Iaj+ZMDwA+BE5zBrOLbHEoh7lBGNh3s/xDKbfsuMVZH9gUqnJ3XlQGb/ch/V/pA9rPEvOZ/pqII+dHJUkQlvSWxt6LkAFnPhU6qsJ0K1q3dsp9RHaILuCoam32AiFPSSR4+Yd+3skYBdg7e66TuScbCXI1A6d1wMCpdrm0WMVVMrdmYPGJ24QzcUVJiipU2OCBHvM4PbjavwQtRjCmFHCwxVp/S4+gUvdLL2RcBTUdXZDzJL+1sNjK5iV2kiarA=
  app: hackduke-api
  on:
    repo: hack-duke/hackduke-api
