typeform:
  every:
    - "90m"
  args: "sync"
  class: Typeform
  queue: high
  description: Syncs database with typeform entries
  rails_envs: development, production, staging

mailchimp_subscribe:
  every:
    - "55m"
  args: "subscribe"
  class: Mailchimp
  queue: high
  description: Unsubscribe to sync mailchimp with database
  rails_env: development, production, staging

mailchimp_unsubscribe:
  every:
    - "60m"
  args: "unsubscribe"
  class: Mailchimp
  queue: high
  description: Subscribe to sync mailchimp with database
  rails_env: development, production, staging