typeform:
  every:
    - "30m"
  args: "sync"
  class: Typeform
  queue: high
  description: Syncs database with typeform entries
  rails_envs: development, production, staging

mailchimp_subscribe:
  every:
    - "30m"
  args: "sync"
  class: Mailchimp
  queue: high
  description: Unsubscribe to sync mailchimp with database
  rails_env: development, production, staging
